-- Certifications and comparable products were generated by the LLM enrichment.
-- They are factual claims shown to shoppers (EU Directive 2024/825 applies to
-- sustainability labels from 2026-09-27), so they now come only from merchant
-- metafields `cap.certifications` and `cap.comparison_tags`. Clear the
-- generated values; the next enrichment of each product refills them from
-- those metafields.
UPDATE "products_enriched"
SET "certifications" = ARRAY[]::TEXT[],
    "comparison_tags" = ARRAY[]::TEXT[]
WHERE cardinality("certifications") > 0
   OR cardinality("comparison_tags") > 0;
